"""
Django settings for peniel_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-oz36w2$-8r@7^+%y2bg6y^%icidr=4&t!--w+2dmi!y=wxrd1k')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',                        # Aplicação de autenticação personalizada
    'core',                         # Aplicação principal do sistema
    'users',                        # Aplicação de gerenciamento de usuários
    'tesouraria',                    # Aplicação de gestão financeira e tesouraria
    'suporte',                      # Aplicação de suporte e atendimento
    'crispy_forms',                 # Necessário para renderização de formulários
    'crispy_bootstrap5',            # Tema Bootstrap 5 para o Crispy Forms
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'peniel_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'suporte.context_processors.notificacoes_suporte',          # Adiciona as notificações de suporte em todas as páginas
            ],
        },
    },
]

WSGI_APPLICATION = 'peniel_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': os.getenv('DB_NAME'),
    #     'USER': os.getenv('DB_USER'),
    #     'PASSWORD': os.getenv('DB_PASSWORD'),
    #     'HOST': os.getenv('DB_HOST'),
    #     'PORT': os.getenv('DB_PORT'),
    #     'OPTIONS': {
    #         'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    #     },
    # }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Caminho onde o Django procurará pelos arquivos de tradução (.po e .mo)
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Configurações de Mídia (Uploads de Usuários)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'


# Autenticação personalizada
AUTHENTICATION_BACKENDS = [
    'login.backends.EmailBackend',  # Ajustado para o app 'login' definido em INSTALLED_APPS
]

AUTH_USER_MODEL = 'users.Usuario'

LOGIN_URL = '/login/'  # Caminho explícito para garantir redirecionamento correto

# Configurações de Sessão
# https://docs.djangoproject.com/en/5.2/ref/settings/#sessions
SESSION_COOKIE_AGE = 1800  # 1800 segundos (30 minutos) de inatividade para expirar a sessão

# CORREÇÃO CRÍTICA: Definir como False é essencial para o logout por inatividade.
# Quando True, a sessão é salva em TODAS as requisições, reiniciando o timer
# de inatividade e impedindo o logout, mesmo em chamadas AJAX protegidas.
SESSION_SAVE_EVERY_REQUEST = False

# Garante que a expiração da sessão seja controlada apenas por SESSION_COOKIE_AGE.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Configurações do Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
