# Generated by Django 6.0.2 on 2026-02-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='titulo',
            new_name='assunto',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='descricao',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mensagem',
            field=models.TextField(default='', verbose_name='Mensagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.CreateModel(
            name='TicketResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Message')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='suporte.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ticket Reply',
                'verbose_name_plural': 'Ticket Replies',
                'ordering': ['criado_em'],
            },
        ),
    ]
